module.exports = {
  title: `Luiz Elias`,
  siteUrl: `https://www.gatsbyjs.org`,
  description: `Luiz Elias' Portfolio`,
  social: [
    { name: "", url: "" },
    { name: "", url: "" },
  ],
  projects: [
    {
      url: "https://luppus.net",
      repo: {
        back: "https://github.com/kalfritz/lupus-server/",
        front: "https://github.com/kalfritz/lupus-web/",
      },
      name: "Luppus",
      title: "Real Time Social Media",
      description: "",
      techs: [
        "NodeJS",
        "Express",
        "MongoDB",
        "Postgres",
        "Redis",
        "Sequelize",
        "Docker",
        "Socket.io",
        "HTML5",
        "Javascript",
        "React",
        "Hooks",
        "Redux",
        "Redux-Saga",
        "styled-components",
      ],
    },
    {
      url: "https://ecstatic-kowalevski-946cae.netlify.app/",
      repo: {
        back: null,
        front: "https://github.com/kalfritz/pokemon-store",
      },
      name: "PokeStore",
      title: "Pokemon Store",
      description: "",
      techs: [
        "HTML5",
        "Typescript",
        "React",
        "Hooks",
        "Redux",
        "Redux-Saga",
        "Redux-Persist",
        "styled-components",
        "axios",
      ],
    },
    {
      url: "https://quirky-euler-0b1277.netlify.app/",
      repo: {
        back: null,
        front: "https://github.com/kalfritz/e-commerce",
      },
      name: "RocketShoes",
      title: "Shoes Store",
      description: "",
      techs: [
        "HTML5",
        "Javascript",
        "React",
        "Redux",
        "styled-components",
        "axios",
      ],
    },
    // {
    //   url: "https://dreamy-goodall-1fe579.netlify.app/",
    //   repo: {
    //     front: "https://github.com/kalfritz/vanillajs-booklist",
    //   },
    //   name: "MyBookList",
    //   title: "Book List Platform",
    //   description: "",
    //   techs: ["HTML5", "CSS3", "Javascript", "LocalStorage"],
    // },
  ],
}
